<h1>Who am I ?</h1>
<p>My name is Matthieu Di Blasio and I made this tool in my last of studies in Geneva. This is my thesis.</p>

<br/><br/>
<h1>How to contact me ?</h1>
You can contact me at this mail : <a href="mailto:zendformmaker@gmail.com">zendformmaker at gmail dot com</a><br/>
There'll probably be something to contact me on <a href="http://www.zendformmaker.com">zend form maker website</a> soon.<br/>
<br/>

<h1>Update, socializing, or idk</h1>
This tool's updates can be found on github, look for Sarlak's repository or search Zend Form Maker ;)<br/>
Or just click on this link :
<a href="https://github.com/sarlak/Zend-Form-Maker">Zend Form Maker on github</a><br/>
