<h1>Welcome to Zend Form Maker's home page</h1>
<br/>

<h2>Explanations</h2>
<p>
This is the first version of Zend Form Maker, design is pretty much missing ... details. <br/> 
I'm not really good at it, and I did this tool alone so please be tolerant with me, I'll do something about it soon, promise ;)<br/>
And please, forgive me for the approximative english used everywhere in the tool, I speak french and did my best, I'll correct my mistakes as fast as possible ;)<br/>
</p>
<br/>

<h2>What to do now ?</h2>
<p>I suggest you to go to the "form lists" link in the menu and to create your first form there.</p>

<br/>
<h2>Informations</h2>
<p>
    In the directory "application/configs", there is an application.ini file. <br/>
    Some configuration keys are there with the zfm prefix.<br/> 
    You can change some settings there but it's more advised to know what you do before you do it.<br/>
	<br/>
</p>

<p>
    In the public directory, you'll find a subdirectory "resources". This is <b>your</b>b> directory, 
    everything you need to touch should be in here.<br/>
	<br/>
</p>

<p>
    I suggest you to put there :<br/>
    - The font used with the captcha image<br/>
    - The images you would use in the form<br/>
    - Your custom decorators files<br/>
    - Your CSS files needed to display the form while previewing or testing it. <br/>
    <i>All the css files of this directory will be included in these case.</i><br/>
	<br/>
</p>

<p>
You'll also find a "xml" subdirectory which will contains all the form you'll make with my tool.<br/>
And finally, the form_made subdirectory will contains the class generetad by the tool for you.<br/>
<br/>
</p>

<p>
I hope you'll like this tool, don't hesitate to <a href="<?php echo $this->url(array('controller' => 'Index', 'action' => 'About')); ?>">contact me</a> if you got any question, suggestion, bug, etc... <br/>
I'll be glad to have some feedback.
</p>